version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  test:
    parameters:
      test-dir:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: "14"
          install-yarn: true
#          yarn-version: "1.22.18"
      - run:
          name: "Display information"
          command: |
            echo "## Date: "
            date
            echo ""
            echo "## Node Version: "
            node -v
            echo ""
            echo "## NPM Version: "
            npm -v
            echo ""
            echo "## YARN Version: "
            yarn -v
      - run:
          name: Run YARN tests
          command: |
            npm config set scripts-prepend-node-path auto \
            && yarn --ignore-engines \
            && cd << parameters.test-dir >> \
            && yarn --ignore-engines \
            && yarn test -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test_output/mocha.xml
      - store_test_results:
          path: test_output

workflows:
  run-node-tests:
    jobs:
      - test:
          matrix:
            parameters:
              test-dir:
                - "./"
                - "packages/lib/ajax-save"
                - "packages/lib/array.merge"
                - "packages/lib/array.dedup"
                - "packages/lib/array.search.js"
                - "packages/lib/create-el"
                - "packages/lib/call-func"
                - "packages/lib/delegation.js"
                - "packages/lib/d3-lib"
                - "packages/lib/get-cookie"
                - "packages/lib/getoffset"
                - "packages/lib/get-object-value"
                - "packages/lib/get-random-id"
                - "packages/lib/get-scroll-info"
                - "packages/lib/get-style"
                - "packages/lib/get-storage"
                - "packages/lib/non-worker"
                - "packages/lib/set-object-value"
                - "packages/lib/seturl"
                - "packages/lib/to-percent-js"
                - "packages/lib/with-array"
                - "packages/organism-react-ajax"
                - "packages/organism-react-animate"
                - "packages/organism-react-code"
                - "packages/organism-react-d3-axis-chart"
                - "packages/organism-react-d3-piechart"
                - "packages/organism-react-d3-uml"
                - "packages/organism-react-graph"
                - "packages/organism-react-html2canvas"
                - "packages/organism-react-i13n"
                - "packages/organism-react-iframe"
                - "packages/organism-react-navigation"
                - "packages/organism-react-popup"
                - "packages/organism-react-sort-by"
                - "packages/organism-react-tag-input"
