import { OBJ_SIZE as size } from "reshow-constant";
export function constant(v: any): () => any;
export function union(...arr: any[]): any;
export function isEmpty(v: any): boolean;
export function isUndefined(val: any): boolean;
export function isFunction(func: any): boolean;
export function transform(obj: any, callback: any, result: any): any;
import { HAS as has } from "reshow-constant";
export function values(obj: any): any[];
export function calMax(p1: any, ...other: any[]): number;
export function calMin(p1: any, ...other: any[]): number;
export function minBy(obj: any, func: any): any;
export function range(n: any): any[];
export function rangeStep(start: any, end: any, step: any, fromRight: any): any[];
export function flattenDownDepth(array: any, result: any, depth: any): any;
export function find(obj: any, func: any): undefined;
export function pick(obj: any, arr: any): {};
export function mapValues(obj: any, func: any): {};
export function zipObject(a1: any, a2: any): {};
export function now(): any;
export { size, has, uniqueId };
